86 improve logging feedback code check for erros or 4xx return code etc validation
dto-btn/ssc-assistant pull request #102
Opened 2024-05-08 15:56 UTC by kyleaitken

This MR adds toast/alert messages to the chat for API errors and for successful feedback submission. The alerts do not persist across browser refreshes, but continue to show in chat otherwise unless they are dismissed.

2024-05-08 15:58 UTC, kyleaitken commented on app/frontend/src/components/FeedbackForm.tsx
> -          <Typography variant="subtitle2" align="left" style={{ paddingLeft: "24px" }}>{t("msg.opt")}</Typography>
got rid of the thank you message since it shows as a toast/alert now

2024-05-08 15:58 UTC, kyleaitken commented on app/frontend/src/api/models.ts
> +type ChatItem = Message | Completion | ToastMessage;
type solution for the variable array used in chatHistory state

2024-05-08 16:00 UTC, kyleaitken commented on app/frontend/src/App.tsx
> +  }
added typeguard functions

2024-05-08 16:00 UTC, kyleaitken commented on app/frontend/src/App.tsx
> +
I noticed this API call was replicated twice in the file, so i just made it it's own function to avoid that

2024-05-08 16:01 UTC, kyleaitken commented on app/frontend/src/App.tsx
>      };
userMessages are no longer completions as we discussed

2024-05-08 16:02 UTC, kyleaitken commented on app/frontend/src/App.tsx
> +    sendApiRequest(request);
again, the try/catch block for the API call was replicated twice so I made it its own function, sendApiRequest

2024-05-08 16:03 UTC, kyleaitken commented on app/frontend/src/App.tsx
> +      };
Making a ToastMessage for feedback submission

2024-05-09 14:59 UTC, kyleaitken commented on app/frontend/src/i18n/locales/fr.json
> +    "chat.unknownError": "Une erreur inconnue est survenue"
idk if these are the correct translations

2024-05-10 11:10 UTC, GuillaumeTurcotte requested changes

2024-05-10 11:10 UTC, GuillaumeTurcotte commented on app/frontend/src/i18n/locales/fr.json
> +    "feedback.success": "Retour soumis, merci!",
"Avis soumis, merci !"

2024-05-10 11:10 UTC, GuillaumeTurcotte commented on app/frontend/src/i18n/locales/fr.json
> +    "feedback.fail": "Erreur de soumission de retour",
"Erreur lors de l'envoi de l'avis."

2024-05-10 14:19 UTC, GuillaumeTurcotte approved these changes

2024-05-10 14:19 UTC, merged